services:
  bdService:
    #image: postgres:17
    image: docker.io/library/postgres:17
    container_name: bd_genomas_services
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - genomas_network

networks:
  genomas_network:
    driver: bridge
volumes:
  db_data:
