services:
  bdService:
    image: postgres:17
    container_name: bd_service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  genomas:
    build:
      context: .
      dockerfile: dockerfile.bdService
    container_name: genomasApp
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@bdService:5432/${POSTGRES_DB}
    volumes:
      - ./:/app
    depends_on:
      - bdService
volumes:
  db_data:
